### ISSUE TITLE
Feature Request or Question: Trigger a specific taskID through adb

### ISSUE THREAD

**Issue by CircuitGuy** [transistorsoft/flutter_background_fetch#132]
**Is your feature request related to a problem? Please describe.**
Possibly just missing documentation... If you add a custom task, is there a way to trigger it through adb or any other way?  

The documentation has a perfect example where "com.transistorsoft.customtask" is added as a custom one-shot task alongside the 'main' task.

However, the adb command "adb shell cmd jobscheduler run ..." doesn't seem to have a way to inject the custom task ID, so only the 'main' task can run.

**Describe the solution you'd like**
adb shell cmd jobscheduler<.CustomTaskID> run -f <your.application.id> 999 

**Describe alternatives you've considered**
(None) May not be possible given the way adb works.  Alternative is to 'mask off' code for testing.

**Additional context**
(None)

**Comment by christocracy** [comment]
Sorry, it's not possible to simulate Android `scheduleTask`.

**Comment by christocracy** [comment]
The `999` you see here is the `JobScheduler` `jobId`.  This is hard-coded for the `fetch` task.

`scheduleTask` creates its `jobId` from `String#hashcode` of the `taskId`.  I guess if you can figure out the `Java` hashcode of your `taskId`, it'd be possible to trigger it.  I guess I could `Log.d` the `hashcode`.

You certainly won't be able to simulate a task when using `useAlarmManager: true`, since that uses `AlarmManager`.  It won't be so easy to trigger `AlarmManager` from `adb shell`, I think.
