### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Puspharaj** [transistorsoft/flutter_background_fetch#137]
Thanks for the awesome plugin by the way this warning occurs every time when the event occurs┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (12580): │ #0   HomeRepository._onBackgroundFetch 
package:engine_sense/data/home_repository.dart:341
I/flutter (12580): │ <asynchronous suspension>
I/flutter (12580): │ #1   BackgroundFetch.configure.() 
package:background_fetch/background_fetch.dart:377
I/flutter (12580): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (12580): │ ⛔ Bad state: Stream has already been listened to.

**Comment by christocracy** [comment]
The issue template is not *optional*, it’s required:

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.
