### ISSUE TITLE
[QUESTION] - task taking more than 15 minutes to run with the phone locked

### ISSUE THREAD

**Issue by lscavalcante** [transistorsoft/flutter_background_fetch#200]
Because when I activate a task and lock the phone in a few moments, the plugin takes more than 15 minutes to run the task, I am using the same code from the example of the documentation for testing.

**Comment by christocracy** [comment]
Ignored issue template.

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.
