### ISSUE TITLE
[BUG]After upgrading to Flutter 2.0, Headless Task not working after app is terminated

### ISSUE THREAD

**Issue by braddlly** [transistorsoft/flutter_background_fetch#220]
Hello.

I've been using the app well so far. 
However, after upgrading to Flutter 2.0, Headless Task does not work.

*pubspec.yaml
background_fetch:
    git:
      url: https://github.com/transistorsoft/flutter_background_fetch

please. help me.

**Comment by christocracy** [comment]
Ignored issue template.

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.
