### ISSUE TITLE
[BUG] BackgroundFetch.status; alway return 2

### ISSUE THREAD

**Issue by moosalim** [transistorsoft/flutter_background_fetch#268]
**Your Environment**
* Plugin version: 1.0.3
* Platform: Android
* OS version: Android 11
* Device manufacturer / model: Redmi Note 8
* Flutter info (`flutter info`, `flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0 21A344 darwin-arm, locale en-OM)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
• No issues found!
```

* Plugin config
```
   BackgroundFetch.configure(
        BackgroundFetchConfig(
          minimumFetchInterval: 60,
          forceAlarmManager: false,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresStorageNotLow: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.NONE,
        ),
        _onBackgroundFetchTimeout);
```
**To Reproduce**
1. Run plugin config `BackgroundFetch.configure(...`
2. Run plugin stop `BackgroundFetch.stop();`
3. Run plugin status `BackgroundFetch.status;`
4. plugin status return 2 

**Debug logs**
`zsh: no matches found: *:S
`
**Additional context**
`BackgroundFetch.status;` always return `2 `even if the status is is executed after `BackgroundFetch.stop();`

**Comment by christocracy** [comment]
`.status()` does not return information about whether the plugin is *started* or *stopped*.  It returns information about whether the app *has permission* to execute fetch or not.  This is primarily an iOS thing, where only iOS has the ability for a user to "disable background fetch" (otherwise known as *background refresh*).

![](https://dl.dropbox.com/s/pwvlu4ntu8gb250/Screen%20Shot%202022-01-13%20at%208.13.50%20PM.png?dl=1)

For Android, the plugin essentially [*always* returns `FETCH_AVAILABLE (2)`](https://github.com/transistorsoft/transistor-background-fetch/blob/6a40d004e24212a585ac99fd0e22c97501652aae/android/tsbackgroundfetch/src/main/java/com/transistorsoft/tsbackgroundfetch/BackgroundFetch.java#L206-L208).

**Comment by marcellplentific** [comment]
Hi @christocracy! There is a setting in Android for enabling/disabling background fetch for particular apps.
It doesn't seem to be working, if I disable it the background fetch callback is still called.
Is this setting related to this, or it's something else?

<img width="375" alt="Screenshot 2022-12-29 at 14 27 40" src="https://user-images.githubusercontent.com/100558085/209959655-bf174fdf-8179-4ae6-9457-afc5c3a7dead.png">

Also, this says that data saving mode is also disabling the background fetch:
https://www.avg.com/en/signal/restrict-background-data

Thanks!
