### ISSUE TITLE
[BUG]When I re-build Gradle, I found like following 

### ISSUE THREAD

**Issue by yeminsoe** [transistorsoft/flutter_background_fetch#290]
**Android**
background_fetch-0.7.3/android/src/main/java/com/transistorsoft/flutter/backgroundfetch/HeadlessTask.java:23: error: ApplicationInfoLoader is not public in io.flutter.embedding.engine.loader; cannot be accessed from outside package
import io.flutter.embedding.engine.loader.ApplicationInfoLoader;

**Comment by christocracy** [comment]
Ignored issue template.

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.
