### ISSUE TITLE
no way to fetch when app is killed? 

### ISSUE THREAD

**Issue by kotran88** [transistorsoft/flutter_background_fetch#338]
it keep record it when app is in background but it seems not recording it when app is terminated. 
for this plugin, there is no way to do it?

**Comment by christocracy** [comment]
This plug-in supports both iOS and Android and the behaviour of each is *completely* different.

that’s why there’s an issue template (which you ignored), that asked you to provide some helpful information, including **Platform**:

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by christocracy** [comment]
Thanks for your feedback @neiljaywarner

**Comment by Taymindis** [comment]
> @kotran88 this plugin does work even when app is terminated, that's one of its very best features.

Is this plugin work for IOS? i thought is not working ?
