### ISSUE TITLE
BackgroundFetchPlugin.java  uses or overrides a deprecated API. 

### ISSUE THREAD

**Issue by amit98-Flutter** [transistorsoft/flutter_background_fetch#360]
Hey, Thanks for providing this package.

Lately, I have been seeing this warning in the logs whenever I run my app. I am not sure how long this warning been showing for but I noticed it fairly recently.

![image](https://github.com/transistorsoft/flutter_background_fetch/assets/104322680/7b0a9003-945e-4528-9fec-978d5fdc07ca)

**Comment by christocracy** [comment]
The issue template is not optional, it's required.

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by agunbuhori** [comment]
the same problem

**Comment by christocracy** [comment]
Why is it a “problem”?

**Comment by tulioccalazans** [comment]
This warning continues in version 1.3.2.
So that you can reproduce, just first call "flutter clean" and then "flutter run".

**Comment by christocracy** [comment]
This harmless warning is due to code left behind to support older versions of Flutter from about two years ago.  This is from code which can never be reached by the latest Flutter SDKs.

**Comment by derrickgw** [comment]
@amit98-Flutter The issue is currently caused by the `PluginRegistry` import statements in `BackgroundFetchPlugin.java`.  The code that requires those was [recently removed](https://github.com/transistorsoft/flutter_background_fetch/commit/1f7c4ac91c5e0fe4c126d33e1e953849849e85e9#diff-8d85773763b5b14a47e3cfa3792345a937c89872b9567e867b9f60d347a8d742).  You can safely ignore the warning, or you could monkey patch the file by removing the two import statements that mention `PluginRegistry`.
