### ISSUE TITLE
can't apply android configuration

### ISSUE THREAD

**Issue by mohamed-selim-a** [transistorsoft/flutter_background_fetch#53]
regarding the android configuration 
in the file 
android/app/build.gradle

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

// flutter_background_geolocation (must be placed after the lines above)
+Project background_geolocation = project(':flutter_background_geolocation')
+apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

the first 2 lines don't exist, and after placing them, i've got an error

Could not get unknown property 'flutterRoot' for project ':app' of type org.gradle.api.Project.

**Comment by christocracy** [comment]
Do **NOT** ignore the issue template.  Copy [the text], edit your issue and provide the requested information.

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

**Additional context**
Add any other context about the problem here.

**Comment by christocracy** [comment]
Closed for ignoring issue template
