### ISSUE TITLE
Its Working on Android but on IOS not working , i wait 1 day , but still not working,

### ISSUE THREAD

**Issue by altafkhan8719** [transistorsoft/flutter_background_fetch#70]
Mac
* Plugin version: background_fetch: ^0.4.0
* Platform: iOS
* OS version: 
* Device manufacturer / model: IPhone 11 Pro (on Simulator)
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**To Reproduce**
Source Code To Reproduce
[backgroundFetch.txt](https://github.com/transistorsoft/flutter_background_fetch/files/4070655/backgroundFetch.txt)

**Comment by christocracy** [comment]
Did you simulate fetch in Simulator?  If it works in simulator, that’s all you need to know that it works.

iOS can take days before it settles in and starts operating automatically.  This has been asked dozens of times in the issues.  Search the issues.

**Comment by AndroidGecko** [comment]
Hey @christocracy 
I found the same issue today and it seems to me that it is a valid one, although I didn't have enough time to debug this properly. Here is my thinking:

When implementing ios in a pure native way - once bg fetch is set up properly with 15mins delay it should fire at around ~30mins intervals initially and then adjust. I know that empirically from my apps. My testing with your implementation resulted in ~10h for the initial fetch to occur. This doesn't feel right.

The thing is that iOS determines the intervals not only based on 15mins value but also based on values returned to completion handler (see [doc](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refresh))
so that if `.noData` is returned the interval will occur less and less frequently. On the other hand, if `.newData` is returned to completion handler -- the bg fetch will be more or less in ~30mins intervals.

I was quickly skimming your code to see how that result is passed to completion handler but couldn't find it - no knowledge of obj c.

I could be wrong of course about some things in your implementation -- in that case it would be great if you could shed some light on how the result type is passed back to the OS.

Thanks for the plugin btw!

**Comment by AndroidGecko** [comment]
Looks like you have defined the result constants in here:
https://github.com/transistorsoft/flutter_background_fetch/blob/master/lib/background_fetch.dart#L340
is there a method that I can use with them? `BackgroundFetch.finish()` takes String.

**Comment by christocracy** [comment]
The README in master references version `0.5.0`, which is a migration to the new iOS [BGTaskScheduler](https://developer.apple.com/documentation/backgroundtasks/bgtaskscheduler?language=objc) API.  The [old API](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623125-application?language=objc) was deprecated in iOS 13.

The new `BGTaskScheduler` API no longer requires a [UIBackgroundFechResult](https://developer.apple.com/documentation/uikit/uibackgroundfetchresult?language=objc)

For those not yet implementing the new `BGTaskScheduler` API (or for those apps running iOS < 13), the plugin hard-codes `UIBackgroundFetchResultNewData`.

I suggest installing the `/example` app in this repo.  It renders a List of fetch events.  I typically seeing 4 events / hour.  And of course, iOS halts fetch events when the app is manually terminated by the user.

**Comment by christocracy** [comment]
`BackgroundFetch.finish` takes a `String` now because the new iOS `BGTaskScheduler` API now supports scheduling arbitrary background-tasks in addition the default periodic fetch task, via new method `scheduleTask` (Android supports `scheduleTask` now too).

`#finish` now needs to differentiate between finishing the usual `fetch` task or one's own arbitrary task scheduled via `#scheduleTask`.
